#!/usr/bin/env zsh
# SPDX-FileCopyrightText: 2023 mattmc3
# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: MIT

# antidote
zstyle ':antidote:bundle' file $ZDOTDIR/zsh_plugins.txt
zstyle ':antidote:bundle' use-friendly-names 'on'

# completions
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:default' list-prompt '%S%M matches%s'

zstyle ':completion:*:*:*:*:*' menu 'no'
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '[%d]'
zstyle ':completion:*:corrections' format '[%d] (%e)'
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*:messages' format '[%d]'
zstyle ':completion:*:warnings' format 'no matches found'
zstyle ':completion:*' format '[%d]'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes

# zephyr
zstyle ':zephyr:plugin:completion' compstyle 'none'
zstyle ':zephyr:plugin:environment' use-xdg-basedirs 'yes'
zstyle ':zephyr:plugin:environment' prepath \
  $CARGO_HOME/bin \
  $GOPATH/bin \
  $HOME/.local/{,s}bin(N)

# fzf-tab
[[ -n $TMUX ]] && zstyle ':fzf-tab:*' fzf-command 'ftb-tmux-popup'
zstyle ':fzf-tab:*' fzf-flags '--preview-window=right:50% --bind=tab:accept'
zstyle ':fzf-tab:*' show-group 'quiet'
zstyle ':fzf-tab:*' switch-group '<' '>'
