#!/usr/bin/env zsh
# SPDX-FileCopyrightText: 2023 mattmc3
# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: MIT

# antidote
zstyle ':antidote:bundle' file ${ZDOTDIR:-HOME}/zsh_plugins.txt
zstyle ':antidote:bundle' use-friendly-names on

# fzf-tab
[[ -n $TMUX ]] && zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
zstyle ':fzf-tab:*' fzf-flags --preview-window=right:50% --bind=tab:accept
zstyle ':fzf-tab:*' show-group quiet
zstyle ':fzf-tab:*' switch-group '<' '>'
